require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
#  TargetRubyVersion: 7.1.3
  NewCops: enable # Decide whether to automatically enable new cops
  SuggestExtensions: false

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 8

RSpec/ExampleLength:
  Max: 10

Rails/I18nLocaleTexts:
  Enabled: false

RSpec/IndexedLet:
  Enabled: false

Metrics/ClassLength:
  Max: 200

Metrics/MethodLength:
  Max: 20